# Generated by Django 5.2.2 on 2025-06-10 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('youtube_music', 'YouTube Music'), ('mixed', 'Mixed')], default='youtube', max_length=20)),
                ('youtube_playlist_id', models.CharField(blank=True, max_length=50, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Playlist Collection',
                'verbose_name_plural': 'Playlist Collections',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['-created'], 'verbose_name': 'Track', 'verbose_name_plural': 'Tracks'},
        ),
        migrations.AddField(
            model_name='playlist',
            name='album',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='playlist',
            name='artist',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='playlist',
            name='duration_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='platform_source',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('youtube_music', 'YouTube Music'), ('mixed', 'Mixed')], default='youtube', max_length=20),
        ),
        migrations.AddField(
            model_name='playlist',
            name='track_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='playlists.playlistcollection'),
        ),
        migrations.CreateModel(
            name='UserPlaylistCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('collections', models.ManyToManyField(related_name='user_collections', to='playlists.playlistcollection')),
                ('tracks', models.ManyToManyField(blank=True, related_name='user_collections', to='playlists.playlist')),
            ],
            options={
                'verbose_name': 'User Playlist Collection',
                'verbose_name_plural': 'User Playlist Collections',
                'ordering': ['-created'],
            },
        ),
    ]
